library(shiny)
library(shinydashboard)
library(shinyWidgets)
library(leaflet)
library(rgdal)
library(dplyr)
library(ggplot2)
library(data.table)
library(ggplot2)
library(readr)
library(tidyverse)

df = read.csv(file='./DF/clean_USD2.csv')
#df2 = read.csv(file='./WV1.csv')
x_axis = read.csv(file='./DF/x_axis4.csv')
citycomp = read_csv(file='./DF/CityComp3.csv')
scaled_longer = read_csv(file='./DF/Scaled_Box.csv')
index = read.csv(file='./DF/Index.csv')
map_world = map_data('world')
city_geo = read.csv(file='./DF/city_geo.csv')

