library(shiny)
library(shinydashboard)
library(shinyWidgets)
library(leaflet)
library(rgdal)
library(dplyr)
library(ggplot2)
library(data.table)
library(ggplot2)
library(readr)
library(tidyverse)

df = read.csv(file='./DF/clean_USD3.csv')
x_axis = read.csv(file='./DF/x_axis5.csv')
citycomp = read_csv(file='./DF/CityComp6.csv')
scaled_longer = read_csv(file='./DF/Scaled_Box2.csv')
index = read.csv(file='./DF/Index2.csv')
city = read.csv(file='./DF/city_geo.csv')
citycompgeo = read_csv(file='./DF/citycomp_geo4.csv')
unscaled_longer = read_csv(file='./DF/Unscaled1.csv')

